# jekyll-theme-MNPP

# site info
title: Todd's Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My Experimental Design
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# author info
author:
  name: Mollia
  url: https://github.com/mollia/
  email: 563560836@qq.com

# Pagination 分页
paginate: 10
paginate_path: "/page:num/" # 分页的url

# Excerpt 摘要
excerpt_separator: "\n\n" # 摘要的分隔符，取第一段
excerpt_max_num: 64 # 摘要的最大长度

# font matter defaults 默认头
defaults:
  - posts:
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# collections 集合
collections:
  ppt:
    output: true
    permalink: /:year-:month-:day/:title
  jekyll:
    output: true
    permalink: /jekyll/:title
# sass （not necessary needed)
sass:
  sass_dir: "/style/sass"

# Plugins 插件
plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - .gitattributes
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - _site/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules/
  - src/
  - README.md
  - tailwind.config.js
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/