# Basic 基础
name: Todd's Blog
author: Todd Zhou
url: https://toddzzf.github.io
baseurl: 
resume_site: https://toddzzf.github.io
description: Thought.Knowledege.Life.
plugins: [jekyll-paginate]
permalink: /:year-:month-:day/:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Social 社交
github_username: ToddZZF
github: https://github.com/ToddZZF
bilibili: https://space.bilibili.com/14158798
mail: mailto:toddzzf@outlook.com
wechat:
qq:
nintendo:
xbox:

# Markdown
highlighter: rouge
markdown: kramdown
kramdown:
  toc_levels: 1..3

# Comments 评论
comments:
  gitalk:
    clientID: 46466568edd862a59169
    clientSecret: 4796ee89765c241e2cc6acc378eec7d6199c027c
    repo: toddzzf.github.io
    owner: ToddZZF
    admin: ToddZZF


# Excerpt 摘要
excerpt_separator: <!--more--> # 摘要的分隔符
excerpt_max_num: 128 # 摘要的最大长度

# Markdown Enhancement 扩展 markdown
sources: bootcdn # bootcdn 或 jsdelivr

## Mathjax
mathjax: false
mathjax_autoNumber: false

## Mermaid
mermaid: false

## Chart
chart: false

## 集合
collections:
  my_ppt:
    output: true
    permalink: /:year-:month-:day/:title
  jekyll:
    output: true
    permalink: /jekyll/:title