baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Todd's Blog"
theme = 'Cockatiel'
pagination.pagerSize = 10

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false